<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="C02YD0SMJGH6" name="pytest" skipped="0" tests="9" time="0.793" timestamp="2020-04-11T10:28:43.208973"><testcase classname="tests.test_app.TestEndpoints" file="tests/test_app.py" line="30" name="test_get_categories" time="0.022"></testcase><testcase classname="tests.test_app.TestEndpoints" file="tests/test_app.py" line="40" name="test_get_transactions" time="0.010"></testcase><testcase classname="tests.test_app.TestEndpoints" file="tests/test_app.py" line="34" name="test_post_categories" time="0.010"></testcase><testcase classname="tests.test_app.TestEndpoints" file="tests/test_app.py" line="44" name="test_post_transaction" time="0.013"></testcase><testcase classname="tests.test_app.TestEndpoints" file="tests/test_app.py" line="26" name="test_server_is_runnning" time="0.029"></testcase><testcase classname="tests.test_app.TestEndpoints" file="tests/test_app.py" line="58" name="test_that_will_fail" time="0.007"><failure message="AssertionError: False is not true">self = &lt;tests.test_app.TestEndpoints testMethod=test_that_will_fail&gt;

    def test_that_will_fail(self):
&gt;       self.assertTrue(False)
E       AssertionError: False is not true

tests/test_app.py:60: AssertionError</failure></testcase><testcase classname="tests.test_db.TestTransactionsDB" file="tests/test_db.py" line="31" name="test_add_and_remove_category" time="0.019"></testcase><testcase classname="tests.test_db.TestTransactionsDB" file="tests/test_db.py" line="71" name="test_add_transaction" time="0.025"></testcase><testcase classname="tests.test_db.TestTransactionsDB" file="tests/test_db.py" line="54" name="test_adding_conflicting_categories" time="0.019"></testcase></testsuite></testsuites>
